name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
            - '*.md'

jobs:
    # build / test
    Build:
        name: Build Package
        runs-on: ubuntu-latest
        steps:
            # Checkout Repo
            - uses: actions/checkout@v4

            # Setup Node
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            # Install Dependencies
            - run: npm i

            # Build Package
            - run: npm run build

            # Run Tests
            - run: npm run test

    # create / release
    Release:
        needs: Build
        name: Create Release Package
        runs-on: ubuntu-latest
        steps:
            # Checkout Repo
            - uses: actions/checkout@v4

            # Setup Node
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            # Show current package
            - name: cat package.json
              run: cat ./package.json

            # Install Dependencies
            - run: npm i

            # Build package
            - run: npm run build

            # Bump version, tag commit and generate a changelog
            - name: Conventional Changelog Action
              uses: TriPSs/conventional-changelog-action@v3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  git-message: 'chore(release): {version}'
                  tag-prefix: 'v'
                  output-file: 'CHANGELOG.md'
                  release-count: '10'
                  skip-on-empty: 'false'
                  skip-version-file: 'false'
                  skip-commit: 'false'

            # Publish to NPM
            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}